name: 'TestPublish'
on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: npm run lint

  Test:
    runs-on: macos-13
    needs: Lint
    env:
      GITHUB_CI: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.1

      - name: Run tests 👩🏽‍💻
        run: npm run test

  PublishGithub:
    runs-on: ubuntu-latest
    needs: Test
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish Github Package
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  PublishNpm:
    runs-on: ubuntu-latest
    needs: Test
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish Npm Package
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@example.com"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
